name: Build and Deploy Catalog

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

# Set permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    
    - name: Build catalog
      run: python scripts/build_catalog.py
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: catalog-build
        path: dist/

  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: catalog-build
        path: dist/
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages
        clean: true
        token: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Add a step to deploy to a CDN
    # - name: Deploy to CDN
    #   run: |
    #     # Add commands to deploy to your preferred CDN
    #     # For example, AWS S3 + CloudFront, Netlify, Vercel, etc. 